/**
 * VYOM Publication — Books Catalogue
 * Single source of truth for all book data used across the books listing and detail pages.
 * TODO: Replace with GET /api/v1/books and GET /api/v1/books/:id once backend credentials are available.
 */

export const CATALOGUE = [
  {
    id: '1',
    title: 'Foundations of Modern Research',
    author: 'Dr. Ananya Sharma',
    category: 'Academic & Research',
    year: 2024,
    price: 499,
    pages: 312,
    isbn: '978-81-VYOM-01-1',
    language: 'English',
    description:
      'A comprehensive guide to research methodology, academic writing, and scholarly inquiry for graduate students and early-career researchers. This book bridges the gap between theoretical frameworks and practical research execution.',
    highlights: [
      'Covers quantitative, qualitative, and mixed-methods approaches',
      'Includes real-world case studies from Indian academic institutions',
      'Practical templates for research proposals and literature reviews',
      'Guidance on ethical considerations in academic research',
      'Endorsed by faculty at IIT Delhi and JNU',
    ],
    rating: 4.8,
    reviews: 42,
  },
  {
    id: '2',
    title: 'Advances in Applied Sciences',
    author: 'Prof. Rajiv Mehta',
    category: 'Science & Technology',
    year: 2024,
    price: 599,
    pages: 428,
    isbn: '978-81-VYOM-02-8',
    language: 'English',
    description:
      'An authoritative survey of cutting-edge developments across applied sciences — from materials engineering to biomedical technology.',
    highlights: [
      'Covers 12 applied science disciplines in depth',
      'Peer-reviewed contributions from 18 domain experts',
      'Includes laboratory protocols and experimental data',
      'Indexed in 3 international scientific databases',
      'Suitable for postgraduate and doctoral programmes',
    ],
    rating: 4.7,
    reviews: 31,
  },
  {
    id: '3',
    title: 'Contemporary Literary Studies',
    author: 'Dr. Priya Nair',
    category: 'Literature',
    year: 2024,
    price: 449,
    pages: 256,
    isbn: '978-81-VYOM-03-5',
    language: 'English',
    description:
      'A critical exploration of contemporary literary movements, postmodern narratives, and the evolving landscape of world literature.',
    highlights: [
      'Analyses works from South Asian, African, and Latin American traditions',
      'Engages with postcolonial, feminist, and ecocritical frameworks',
      'Includes close readings of 30+ contemporary texts',
      'Ideal for literature students and academic researchers',
      'Foreword by a Sahitya Akademi award recipient',
    ],
    rating: 4.6,
    reviews: 27,
  },
  {
    id: '4',
    title: 'Economic Perspectives 2024',
    author: 'Dr. Suresh Patel',
    category: 'Non-Fiction',
    year: 2024,
    price: 399,
    pages: 290,
    isbn: '978-81-VYOM-04-2',
    language: 'English',
    description:
      "A timely analysis of India's macroeconomic landscape, fiscal policy, and global trade dynamics in 2024.",
    highlights: [
      'Data-driven analysis of GDP, inflation, and employment trends',
      'Covers Union Budget 2024 implications in detail',
      'Accessible to general readers and policy professionals alike',
      'Includes comparative analysis with BRICS economies',
      'Updated with Q1 2024 economic indicators',
    ],
    rating: 4.5,
    reviews: 19,
  },
  {
    id: '5',
    title: 'Quantum Computing Frontiers',
    author: 'Dr. Vikram Singh',
    category: 'Science & Technology',
    year: 2024,
    price: 699,
    pages: 380,
    isbn: '978-81-VYOM-05-9',
    language: 'English',
    description:
      'An accessible yet technically rigorous introduction to quantum computing — covering qubits, quantum gates, entanglement, and near-term quantum algorithms.',
    highlights: [
      'Covers quantum circuit design and simulation',
      'Includes Python code examples using Qiskit',
      "Explains Shor's and Grover's algorithms in depth",
      'Discusses NISQ-era hardware and its limitations',
      'Suitable for advanced undergraduates and researchers',
    ],
    rating: 4.9,
    reviews: 55,
  },
  {
    id: '6',
    title: 'Post-Colonial Narratives',
    author: 'Prof. Leela Krishnan',
    category: 'Literature',
    year: 2023,
    price: 349,
    pages: 224,
    isbn: '978-81-VYOM-06-6',
    language: 'English',
    description:
      'A scholarly examination of post-colonial literature across South and Southeast Asia.',
    highlights: [
      'Covers writers from India, Sri Lanka, Malaysia, and Singapore',
      "Engages with Fanon, Spivak, and Bhabha's theoretical frameworks",
      'Includes previously unpublished archival material',
      'Winner of the South Asian Literary Critics Award 2023',
      'Recommended reading at 15 Indian universities',
    ],
    rating: 4.7,
    reviews: 38,
  },
  {
    id: '7',
    title: 'Sustainable Development Goals',
    author: 'Dr. Arun Nambiar',
    category: 'Academic & Research',
    year: 2023,
    price: 549,
    pages: 344,
    isbn: '978-81-VYOM-07-3',
    language: 'English',
    description:
      "A comprehensive academic analysis of the UN's 17 Sustainable Development Goals with a focus on South Asia.",
    highlights: [
      'Covers all 17 SDGs with country-level case studies',
      'Includes original field research from 6 Indian states',
      'Policy recommendations for government and NGOs',
      'Foreword by a former UN Environment Programme official',
      'Widely cited in environmental policy literature',
    ],
    rating: 4.6,
    reviews: 24,
  },
  {
    id: '8',
    title: 'The Art of Storytelling',
    author: 'Meera Pillai',
    category: 'Fiction',
    year: 2023,
    price: 299,
    pages: 198,
    isbn: '978-81-VYOM-08-0',
    language: 'English',
    description:
      "A beautifully crafted collection of interconnected short stories exploring the lives of ordinary people in contemporary India.",
    highlights: [
      '12 interconnected short stories set across India',
      'Longlisted for the JCB Prize for Literature',
      'Translated into 3 regional languages',
      'Praised by The Hindu and Indian Express',
      'Ideal for book clubs and literary fiction readers',
    ],
    rating: 4.8,
    reviews: 67,
  },
  {
    id: '9',
    title: 'Molecular Biology Essentials',
    author: 'Prof. Meera Iyer',
    category: 'Science & Technology',
    year: 2023,
    price: 649,
    pages: 410,
    isbn: '978-81-VYOM-09-7',
    language: 'English',
    description:
      'A definitive textbook covering the core principles of molecular biology — from DNA replication to CRISPR technology.',
    highlights: [
      'Covers classical and modern molecular biology',
      'Includes 200+ diagrams and illustrations',
      'Chapter-end questions and answer keys',
      'Aligned with UGC and CSIR NET syllabi',
      'Used in 40+ Indian universities',
    ],
    rating: 4.7,
    reviews: 89,
  },
  {
    id: '10',
    title: "India's Economic Transformation",
    author: 'Dr. Sanjay Kulkarni',
    category: 'Non-Fiction',
    year: 2022,
    price: 449,
    pages: 318,
    isbn: '978-81-VYOM-10-3',
    language: 'English',
    description:
      "A sweeping narrative of India's economic journey from liberalisation in 1991 to the digital economy of the 2020s.",
    highlights: [
      'Covers 30 years of economic policy',
      'Interviews with former Finance Ministry officials',
      'Data visualisations of key economic indicators',
      'Accessible to general and academic readers',
      'Shortlisted for the Business Book of the Year Award',
    ],
    rating: 4.5,
    reviews: 33,
  },
  {
    id: '11',
    title: 'Voices from the Margins',
    author: 'Dr. Kavita Rao',
    category: 'Fiction',
    year: 2022,
    price: 349,
    pages: 242,
    isbn: '978-81-VYOM-11-0',
    language: 'English',
    description:
      'A powerful novel exploring caste, gender, and identity in rural India through the eyes of three women across three generations.',
    highlights: [
      'Winner of the Sahitya Akademi Yuva Puraskar',
      'Translated into 5 languages',
      'Taught in postgraduate literature programmes',
      'Praised for its unflinching social commentary',
      'Adapted for a stage production in 2023',
    ],
    rating: 4.9,
    reviews: 112,
  },
  {
    id: '12',
    title: 'Environmental Policy in South Asia',
    author: 'Dr. Rohit Das',
    category: 'Academic & Research',
    year: 2022,
    price: 499,
    pages: 296,
    isbn: '978-81-VYOM-12-7',
    language: 'English',
    description:
      'A rigorous comparative study of environmental legislation, climate policy, and conservation efforts across India, Bangladesh, Nepal, and Sri Lanka.',
    highlights: [
      'Comparative policy analysis across 4 nations',
      'Includes original environmental impact data',
      'Covers climate agreements and national action plans',
      'Recommended by the Ministry of Environment',
      'Cited in 50+ peer-reviewed articles',
    ],
    rating: 4.6,
    reviews: 21,
  },
  {
    id: '13',
    title: 'Digital Humanities: A Primer',
    author: 'Prof. Arjun Das',
    category: 'Academic & Research',
    year: 2024,
    price: 399,
    pages: 268,
    isbn: '978-81-VYOM-13-4',
    language: 'English',
    description:
      'An accessible introduction to the emerging field of digital humanities — exploring how computational methods are transforming literary analysis and cultural studies.',
    highlights: [
      'Covers text mining, network analysis, and GIS',
      'No prior programming knowledge required',
      'Includes hands-on exercises with open-source tools',
      'Suitable for humanities researchers and students',
      'Foreword by a leading DH scholar from Oxford',
    ],
    rating: 4.4,
    reviews: 18,
  },
  {
    id: '14',
    title: 'The Silent River',
    author: 'Sunita Verma',
    category: 'Fiction',
    year: 2023,
    price: 279,
    pages: 214,
    isbn: '978-81-VYOM-14-1',
    language: 'English',
    description:
      "A lyrical debut novel set along the banks of the Ganga, following a young woman's journey of self-discovery against the backdrop of a changing India.",
    highlights: [
      'Debut novel — critically acclaimed',
      'Shortlisted for the Hindu Literary Prize',
      'Evocative prose rooted in North Indian landscape',
      'Explores themes of memory, loss, and belonging',
      'Book club favourite across India',
    ],
    rating: 4.7,
    reviews: 44,
  },
  {
    id: '15',
    title: 'Computational Linguistics Today',
    author: 'Prof. Priya Nambiar',
    category: 'Science & Technology',
    year: 2024,
    price: 599,
    pages: 356,
    isbn: '978-81-VYOM-15-8',
    language: 'English',
    description:
      'A state-of-the-art survey of computational linguistics — covering NLP pipelines, transformer models, and the linguistic theory underpinning modern language AI.',
    highlights: [
      'Covers BERT, GPT, and multilingual models',
      'Includes Python NLP code examples',
      'Bridges linguistics theory and ML practice',
      'Suitable for NLP researchers and linguists',
      'Endorsed by ACL and EMNLP communities',
    ],
    rating: 4.8,
    reviews: 36,
  },
  {
    id: '16',
    title: 'Philosophy of Mind',
    author: 'Dr. Arun Menon',
    category: 'Non-Fiction',
    year: 2022,
    price: 429,
    pages: 302,
    isbn: '978-81-VYOM-16-5',
    language: 'English',
    description:
      'A rigorous yet accessible exploration of the philosophy of mind — consciousness, qualia, personal identity, and the mind-body problem.',
    highlights: [
      "Engages with Chalmers, Nagel, and Advaita Vedanta",
      'Accessible to readers without a philosophy background',
      'Includes discussion questions for seminars',
      'Widely used in philosophy departments',
      'Praised for its cross-cultural approach',
    ],
    rating: 4.5,
    reviews: 29,
  },
];

/** Lightweight version for listing pages */
export const ALL_BOOKS = CATALOGUE.map(({ id, title, author, category }) => ({
  id, title, author,
  category: category.toUpperCase().replace(' & ', ' & ').replace('ACADEMIC & RESEARCH', 'ACADEMIC'),
}));
